# install: conda env create -f environment.yml
# update:  conda env update -f environment.yml

name: wf1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - ipython
  - jupyter
  - numpy
  - nb_conda
  - matplotlib
  - scipy
  - tqdm
  - scikit-image
  - tifffile
